### ISSUE TITLE
More settings for retrofitting and fine-tuning

### ISSUE THREAD

**Issue by jxmorris12** [jscuds/rf-bert#19]
<img width="1088" alt="Screen Shot 2022-02-22 at 10 54 28 AM" src="https://user-images.githubusercontent.com/13238952/155169313-cbfb7b76-9626-474a-9221-e1e7db25473b.png">

This is Table 2 from [Retrofitting Contextualized Word Embeddings with Paraphrases](https://arxiv.org/pdf/1909.09700.pdf). 

We're missing a couple of the row dimensions (new settings for retrofitting):
- MRPC dataset
- PAN dataset
- Ability to combine multiple things together (Quora + MRPC + PAN)

And most of the column dimensions, various fine-tuning tasks:
- MPQA 
- CR (what is this?)
- SST-2
- SICK-R
- {STS-15, STS-16, STS-Benchmark}
- MRPC
- SICK-E

We certainly don't need to support every scenario, but more would be nice. They claim retrofitting with Sampled Quora gives a ~4% boost in accuracy on MPQA so that could be a good place to start.

**Comment by jscuds** [comment]
## First Steps
1. I'll start w/ MPQA.  I'm going to use Version 3.0 (came out in 2015 so I think it's a reasonable assumption that this is the one Shi used).  The site for the dataset is here [[link](https://mpqa.cs.pitt.edu/corpora/mpqa_corpus/)], and I confirmed it's not on HF `datasets` via this [GH Issue](https://github.com/huggingface/datasets/issues/353#issue-653250611) (which I saw you had some comments on from 18 months ago, haha).
2. I think MRPC in `datasets` is structured similarly to `quora`/`('glue','qqp')`.  The `ParaphraseDatasetElmo` framework _should_ just require me to add a few additional lines to allow for MRPC in retrofitting.
3. CR is "Customer Review Datasets."  I found the [authors' website](https://www.cs.uic.edu/~liub/FBS/sentiment-analysis.html) and under the heading "Data Sets" they have a 5 product review and a 9 product review -- without specification by Shi I'll use the 5 product review.
4. As I come across additional datasets that aren't included in HF's library, I'll put the raw zip files on my Google Drive in a [datasets directory](https://drive.google.com/drive/u/1/folders/1o6HnWQngYwu_cg7X90mrciSU7oXlAQkK)

**Comment by jxmorris12** [comment]
I think the things we added are sufficient at this point
